WebApplicationDrHelp/Controllers/EntradaController.cs
using Capa.AccesoDatos;
using Capa.Presentacion.Extensions;
using Capa.Presentacion.Models;
using Capa.ServiciosDistribuidos.Repositorios;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace WebApplication.Controllers
{
    
  
    public class EntradaController : Controller
    {

        private readonly ApplicationDbContext _context;
        private RAEGlobonetEntities rAEGlobonetEntities = new RAEGlobonetEntities();
        private EntradaRepositorios entradaRepositorios = new EntradaRepositorios();
        // GET: Entrada
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult EntradaDetail (Entrada entity)
        {
            
            
            EntradaModels entradaModels = new EntradaModels
            {
                Id = entity.Id,
                Titulo = entity.Titulo,
                Autor = entity.Autor
                
            };
            
            return View(); 
        }


        [HttpGet]
        public ActionResult EntradaDetails (EntradaModels model)
        {
            Entrada entity = new Entrada
            {
                Id = model.Id,
                Titulo = model.Titulo,
                Autor = model.Autor

            };
            switch (model.ViewAction)
            {
                case ViewActionEnum.Create:
                    this.entradaRepositorios.Add(entity);
                   
                    break;
                case ViewActionEnum.Delete:
                    this.entradaRepositorios.Delete(entity);
                    break;
                case ViewActionEnum.Detail:
                    int datoId = entity.Id;
                    this.entradaRepositorios.FindById(datoId);
                    break;
                case ViewActionEnum.Edit:
                    //this._PaisCatBL.Update(entity);
                    this.entradaRepositorios.Update(entity);
                    
                    break;
                
            }
            return RedirectToAction("Index") ;
        }

        public JsonResult GetEntrada()
        {
            var entrada = entradaRepositorios.All();
            List<EntradaModels> lstObj = new List<EntradaModels>();
            


            foreach (var item in entrada)
            {
                EntradaModels item1 = new EntradaModels();
                item1.Id = item.Id;
                item1.Titulo = item.Titulo;
                item1.Autor = item.Autor;
              
                lstObj.Add(item1);
            }
            return Json(entrada, JsonRequestBehavior.AllowGet);
        }
    }
}

WebApplicationDrHelp/Views/Entrada/EntradaDetail.cshtml
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Entrada</h3>
                <div id="Grid">

                    <form role="form">
                        <div class="form-group">
                            <label>Información General</label>

                        </div>
                        <div class="form-group has-success">
                            <label class="control-label" for="inputSuccess"><i class="fa fa-check"></i>Titulo</label>
                            <input type="text" class="form-control" id="titulo" placeholder="Enter ...">
                        </div>
                        <div class="form-group">
                            <label>Autor</label>
                            <input type="text" class="form-control" id="autor" placeholder="Enter ..."></input>
                        </div>
                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary" onclick="AgregarEntrada()">Agregar</button>
                        </div>
                    </form>

                </div>
                    
            </div>
            
        </div>
    </div>

</div>
<script src="~/Scripts/Entrada/AgregarEntrada.js"></script>

WebApplicationDrHelp/Views/Entrada/Index.cshtml
@using Capa.Presentacion.Extensions
@{
    ViewBag.Title = "Prueba técnica";
}



<div class="row">
    <div class="col-xs-12">

        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Entrada</h3>
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary" onclick="location.href='@Url.Action("EntradaDetail", "Entrada")'">Agregar</button>
                </div>
            </div>
            <div class="box-body">
                <table id="entradas" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Codigo</th>
                            <th>Titulo</th>
                            <th>Autor</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                    <tfoot>


                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>


@section Scripts {

    @Scripts.Render("~/AdminLTE/plugins/datatables/js")
    @Scripts.Render("~/Scripts/Tables/Data")
    <script type="text/javascript" src="~/Scripts/common/utilities.js"></script>
    <script>
    $('[data-toggle=tooltip]').tooltip();
     var actionInitialConf = 'entity-url="@Url.Action("EntradaDetails", "Entrada")" ';

    $("#entradas").DataTable({
    processing: true,
    serverSide: true,
    bFilter: true,
    orderMulti: false,
    bAutoWidth: true,
    sAjaxSource: '@this.Url.Action("GetEntrada")',
    sAjaxDataProp: '',// this links to your controller method from Step 3
    columns:
    [ // You can configure, per property, if it should be sortable, etc. Make sure the names equal the names you gave it in step 1.

            { data: 'Id' },
            { data: 'Titulo' },
            { data: 'Autor' },
            {
                data: null,
                bSortable: false,
                sDefaultContent: "Acciones",
                mRender: function (data, type, full) {

                    console.log(data)
                    actionInitialConfPlusID = actionInitialConf + ' data-Id="' + full.Id + '"';

                       var opciones = {
                            "tipo": 'link',
                            "acciones":
                            [
                                {
                                    "url": '#',
                                    "attr": actionInitialConfPlusID + ' data-viewAction="@ViewActionEnum.Edit.ToString()"',

                                    "texto": 'Editar'
                                },
                                {
                                    "url": '#',
                                    @*"attr": actionInitialConfPlusID + ' data-viewAction="@ViewActionEnum.Detail.ToString()"',*@
                                    "attr": actionInitialConfPlusID + ' data-viewAction="@ViewActionEnum.Delete.ToString()"',
                                    "texto": 'Eliminar'
                                },
                                {

                                    "url": '#',
                                    "attr": actionInitialConfPlusID + ' data-viewAction="@ViewActionEnum.Detail.ToString()"',

                                    "texto": 'Detalle'
                                }

                            ]
                        };
                        return renderizarAcciones("Acciones", opciones);

                }

            }
    ],
                initComplete: function () {
                    var opciones = {
                        "tipo": 'link',
                        "url": '#',
                        "acciones": [{
                            "attr": actionInitialConf + ' data-Id="0" data-viewAction="@ViewActionEnum.Create.ToString()" ',
                            "texto": 'Crear'
                        }]
                    };
                    $(".toolbar").html(renderAction(opciones));//Add button on top of datatable

                }

    });

    </script>
}